#!/usr/bin/env python2
from __future__ import print_function
from astropy.io import fits
import argparse
parser = argparse.ArgumentParser(description='Get information about a fits file.')
parser.add_argument("fname", type=str,help='Name of file.')
parser.add_argument("-c", "--columns",     action='store_true',  help="Print columns.")
parser.add_argument("-g", "--geometry", action='store_true',help='Get shape and wcs information .')
args = parser.parse_args()



hdu = fits.open(args.fname)

print(hdu.info())

if args.columns:
    print(hdu[1].columns)


if args.geometry:
    from enlib import enmap
    shape,wcs = enmap.read_fits_geometry(args.fname)
    print(shape,wcs)
        
hdu.close()
