#!/usr/bin/python

import os,sys,time
import argparse

parser = argparse.ArgumentParser(description='Submit strided/threaded MPI jobs to the BNL Astro Cluster')
parser.add_argument("N", type=str,help='Number of MPI jobs')
parser.add_argument("Command", type=str,help='Command')
parser.add_argument("-t", "--threads",     type=int,  default=1,help="Number of threads / cores to stride")
parser.add_argument("-i", "--include",     type=str,  default="",help="Groups to include")
parser.add_argument("-e", "--exclude",     type=str,  default="",help="Groups to exclude")
parser.add_argument("-n", "--name",     type=str,  default=None,help="Job name")
parser.add_argument("-p", "--priority",     type=str,  default="med",help="Priority")


args = parser.parse_args()

cores = args.N * args.threads
jobname = args.name
nowvar=str(int(time.time()*10))


if jobname is None:
    jobname = nowvar


subcmd = "nohup wq sub -r \"mode:bycore;N:"+cores+";threads: "+args.threads+" ;hostfile: auto;job_name:"+jobname+";priority:"+args.priority+";notgroup:["+args.exclude+"];group:["+args.include+"]\" -c \"source ~/.bash_profile ; source ~/.bashrc ; cd $(pwd) ; OMP_NUM_THREADS=%threads% mpirun -hostfile %hostfile% "+args.Command+" \" > $(pwd)/output"+nowvar+".log 2>&1  &"


os.system(subcmd)
time.sleep(0.3)

